### ISSUE TITLE
config.get(...).uploader is not a function

### ISSUE THREAD

**Issue by lencioni** [Galooshi/happo#211]
I'm working on updating a project from happo 4 to happo 5, and when it tries to upload after running I end up with the following error:

```
TypeError: config.get(...).uploader is not a function
    at /home/travis/build/org/project/node_modules/happo-viewer/lib/uploadLastResult.js:92:35
    at Promise (<anonymous>)
    at uploadLastResult (/home/travis/build/org/project/node_modules/happo-viewer/lib/uploadLastResult.js:82:12)
    at Command.<anonymous> (/home/travis/build/org/project/node_modules/happo/lib/cli.js:74:3)
    at Command.listener (/home/travis/build/org/project/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/home/travis/build/org/project/node_modules/commander/index.js:615:12)
    at Command.parse (/home/travis/build/org/project/node_modules/commander/index.js:458:21)
    at cli (/home/travis/build/org/project/node_modules/happo/lib/cli.js:97:15)
```

I haven't dug in yet but I figured I'd log it here for now.

```json
"happo": "5.0.0-rc.3",
"happo-target-firefox": "5.0.0-rc.6",
```

**Comment by lencioni** [comment]
I'm pretty sure this was because I forgot to add `uploader` to my config file when updating. We should add a check and give a helpful error message in this scenario.
