### ISSUE TITLE
Error on windows finding firefox

### ISSUE THREAD

**Issue by sattaman** [Galooshi/happo#212]
On windows I am gettign the following error: 

> Happo Firefox Target listening on 4567
> Error: Failed to check Firefox version: Error: Command failed: C:\Program Files (x86)\Mozilla Firefox\firefox.exe --version
> 'C:\Program' is not recognized as an internal or external command,
> operable program or batch file.
> 
>     at E:\source\osa\PP\node_modules\happo-target-firefox\lib\checkBrowserVersion.js:14:20
>     at ChildProcess.exithandler (child_process.js:211:5)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:891:16)
>     at Socket.<anonymous> (internal/child_process.js:342:11)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at Pipe._handle.close [as _onclose] (net.js:497:12)
>

**Comment by trotzig** [comment]
First of all, sorry for the late response -- I've been away on a longer vacation. 

I haven't had time to properly test happo on windows machines. This one looks pretty simple to fix however. Were you able to find a workaround? If you have time, I'd love to review a PR for fixing this. I'm happy to assist you in setting up the environment if that would help.
