### ISSUE TITLE
Setting up happo locally

### ISSUE THREAD

**Issue by majapw** [Galooshi/happo#220]
Hi @trotzig,

I'm trying to get happo to run locally on my machine. I created a `FileSystemUploader` as described in other issues, but even before getting to the upload part, I'm seeing an issue where `happo run` consistently errors out before rendering a single component. 

Specifically, I'm seeing:
```
+ happo run
Happo Firefox Target listening on 4567
/Users/maja_wichrowska/code/airlab/repos/dls-web/node_modules/selenium-webdriver/lib/promise.js:2634
        throw error;
        ^

UnknownCommandError: timeouts
    at Object.throwDecodedError (/Users/maja_wichrowska/code/airlab/repos/dls-web/node_modules/selenium-webdriver/lib/error.js:489:11)
    at parseHttpResponse (/Users/maja_wichrowska/code/airlab/repos/dls-web/node_modules/selenium-webdriver/lib/http.js:501:15)
    at doSend.then.response (/Users/maja_wichrowska/code/airlab/repos/dls-web/node_modules/selenium-webdriver/lib/http.js:432:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
From: Task: WebDriver.manage().timeouts().setScriptTimeout(30000)
    at thenableWebDriverProxy.schedule (/Users/maja_wichrowska/code/airlab/repos/dls-web/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at Timeouts._scheduleCommand (/Users/maja_wichrowska/code/airlab/repos/dls-web/node_modules/selenium-webdriver/lib/webdriver.js:1500:25)
    at Timeouts.setScriptTimeout (/Users/maja_wichrowska/code/airlab/repos/dls-web/node_modules/selenium-webdriver/lib/webdriver.js:1483:17)
    at /Users/maja_wichrowska/code/airlab/repos/dls-web/node_modules/happo-target-firefox/lib/initializeWebdriver.js:10:36
    at Promise (<anonymous>)
    at initializeWebdriver (/Users/maja_wichrowska/code/airlab/repos/dls-web/node_modules/happo-target-firefox/lib/initializeWebdriver.js:7:12)
    at /Users/maja_wichrowska/code/airlab/repos/dls-web/node_modules/happo-target-firefox/lib/index.js:43:18
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```
and having a lot of trouble figuring out what might be wrong with my set-up that the selenium web driver is having so much trouble.

Any ideas or more information I could give to help debug?

Thanks!

cc: @sharmilajesupaul

**Comment by majapw** [comment]
Hmm, it seems like my config may not be being set appropriately.

**Comment by majapw** [comment]
JUST KIDDING, this was my b. :/ I had a global happo installed and it was causing unexpected results.

**Comment by trotzig** [comment]
Ah, the old `npm install -g`. 😄 

Glad you figured it out.
